---
title: "SAD space report"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(drake)
library(sadspace)
library(dplyr)
library(ggplot2)
library(ggpmisc)
```

```{r load stuff}

sv <- define_statevars() %>%
  assign_ptable() %>%
  dplyr::filter(p_table != "none")

#di_df <- read.csv(here::here("analysis", "di_dfs.csv"), stringsAsFactors = F)
fs_size_dat <- read.csv(here::here("analysis", "fs_size_dat.csv"), stringsAsFactors = F)
di_summary_df <- read.csv(here::here("analysis", "di_summary_df.csv"), stringsAsFactors = F)

```

Here is the range of S and N space covered:

```{r plot sn space, fig.dim = c(3.5, 3.5)}

ggplot(sv, aes(s0, n0, color = n0/s0)) +
  geom_point() +
  theme_bw() +
  scale_color_viridis_c(option = "plasma") +
  theme(legend.position = "top")

ggplot(sv, aes(log(s0), log(n0), color = log(n0/s0))) +
  geom_point() +
  theme_bw()+
  scale_color_viridis_c(option = "plasma")+
  theme(legend.position = "top")
```

Things are generally easier to see on the log axis, so let's stick with that.

## Size and unique elements from FS

Here is how the size of the feasible set varies with S, N, and N/S:

```{r plot size of fs 1}
# 
# fs_size_dat <- di_df %>%
#   select(s0, n0, nparts, nunique) %>%
#   distinct() %>%
#   mutate(log_nparts = log(as.numeric(nparts)),
#          log_nunique = log(nunique))

ggplot(fs_size_dat, aes(log(s0), log(n0), color =log_nparts)) +
  geom_point() + 
  theme_bw()+
  scale_color_viridis_c(option = "plasma", begin = .1, end = .8)+
  theme(legend.position = "top")

```


This is *on a log scale*, so up in that right corner is *1.942426e+130*. 

```{r cv in space}

di_summary_df <- di_summary_df %>%
  mutate(cv_skew = sd_skew/ mean_skew,
         cv_simpson = sd_simpson/mean_simpson)

ggplot(filter(di_summary_df, !is.infinite(sd_skew), !is.infinite(mean_skew), nparts >2, s0 >= 3), aes(log(s0), log(n0), color = log(cv_skew))) +
  geom_point() +
  scale_color_viridis_c() +
  theme_bw()

ggplot(filter(di_summary_df, !is.infinite(sd_simpson), !is.infinite(mean_simpson), nparts >2, s0 >= 2), aes(log(s0), log(n0), color = log(cv_simpson))) +
  geom_point() +
  scale_color_viridis_c() +
  theme_bw()

```

```{r cv v nparts}



ggplot(filter(di_summary_df, s0 >= 3, !is.infinite(sd_skew), !is.infinite(mean_skew), nparts > 2), aes(log_nparts, mean_skew, color = (log(s0)))) +
  geom_point() +
  theme_bw() +
  geom_vline(xintercept = 10) +
  scale_color_viridis_c()


ggplot(filter(di_summary_df, s0 >= 3, !is.infinite(sd_skew), !is.infinite(mean_skew), nparts > 2), aes(log_nparts, sd_skew, color = (log(s0)))) +
  geom_point() +
  theme_bw() +
  geom_vline(xintercept = 10) +
  scale_color_viridis_c()

ggplot(filter(di_summary_df, s0 >= 3, !is.infinite(sd_skew), !is.infinite(mean_skew), nparts > 2), aes(log_nparts, cv_skew, color = (log(s0)))) +
  geom_point() +
  theme_bw() +
  geom_vline(xintercept = 10) +
  scale_color_viridis_c()



ggplot(filter(di_summary_df, s0 >= 3, !is.infinite(sd_simpson), !is.infinite(mean_simpson), nparts > 2), aes(log_nparts, mean_simpson, color = (log(s0)))) +
  geom_point() +
  theme_bw() +
  geom_vline(xintercept = 10) +
  scale_color_viridis_c()


ggplot(filter(di_summary_df, s0 >= 3, !is.infinite(sd_simpson), !is.infinite(mean_simpson), nparts > 2), aes(log_nparts, mean_simpson, color = (log(s0)))) +
  geom_point() +
  theme_bw() +
  geom_vline(xintercept = 10) +
  scale_color_viridis_c()

ggplot(filter(di_summary_df, s0 >= 3, !is.infinite(sd_simpson), !is.infinite(mean_simpson), nparts > 2), aes(log_nparts, sd_simpson, color = (log(s0)))) +
  geom_point() +
  theme_bw() +
  geom_vline(xintercept = 10) +
  scale_color_viridis_c()

ggplot(filter(di_summary_df, s0 >= 2, !is.infinite(sd_simpson), !is.infinite(mean_simpson), nparts > 2), aes(log_nparts, cv_simpson,color = (log(s0)))) +
  geom_point() +
  theme_bw() +
  geom_vline(xintercept = 10)+
  scale_color_viridis_c()

```
