---
title: "SAD space report"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(drake)
library(sadspace)
library(dplyr)
library(ggplot2)
library(ggpmisc)
```

```{r load a fs}

fs_files <- list.files(path = here::here("analysis", "reports"), pattern = "fs_")

fs_list <- lapply(fs_files, FUN = read.csv, stringsAsFactors = F)
```

```{r diffs}

fs_diff <- function(two_fs) {
  return(sum(abs(two_fs[1, ] - two_fs[2, ])) / (2 * sum(two_fs[1,])))
}

fs_r2 <- function(two_fs, log = F) {
  two_fs <- as.matrix(two_fs)
  
  focal <- two_fs[1,]
  compare <- two_fs[2,]
  
  if(log) {
    
    focal <- log(focal)
    compare <- log(compare)
  } 
  
  focal_mean <- mean(focal)
  
  numer <- sum((focal - compare) ^ 2)
  denom <- sum((focal - focal_mean) ^ 2)
  1 - (numer/denom)
}

proportion_off <- function(two_fs) {
    two_fs <- as.matrix(two_fs)

  abs_diff <- sum(abs(two_fs[1, ] - two_fs[2, ])) / 2
  
  abs_diff / sum(two_fs[1, ])
  
}

fs_cd <- function(two_fs) {
  two_fs <- as.matrix(two_fs)
  fs_lm <- lm(two_fs[1, ]  ~ two_fs[2, ])
  return( summary(fs_lm)$r.squared )
}

fs_diff_sampler <- function(fs_set) {
  
  pair <- sample((unique(fs_set$sim)), size = 2, replace = F)
  
  two_fs <- dplyr::filter(fs_set, sim %in% pair) %>%
    dplyr::select(abund, sim, rank) %>%
    tidyr::pivot_wider(names_from = rank, values_from = abund) %>%
    dplyr::select(-sim)
  
  r2 <- fs_r2(two_fs)
  r2_log <- fs_r2(two_fs, log = T)
  cd <- fs_cd(two_fs)
  prop_off <- proportion_off(two_fs)
  return(data.frame(
    sim1 = min(pair),
    sim2 = max(pair),
    r2 = r2,
    r2_log = r2_log,
    cd = cd,
    prop_off = prop_off,
    s0 = ncol(two_fs),
    n0 = sum(two_fs[1, ])
  ))
}

set.seed(1977)

fs_diffs_list <- lapply(fs_list, FUN = function(fs) return(bind_rows(replicate(n = 100, expr = fs_diff_sampler(fs), simplify = F))))

fs_s <- bind_rows(fs_list)
fs_diffs <- bind_rows(fs_diffs_list) %>%
  distinct_at(c("s0", "n0", "sim1", "sim2", "r2", "r2_log", "cd", "prop_off"))
```

```{r plots, fig.width = 2, fig.height = 32}

ggplot(fs_s, aes(x = rank, y = abund, group = sim)) +
  geom_line(alpha = .01) +
  theme_bw() +
  facet_wrap(vars(s0, n0), scales = "free", ncol = 1)

ggplot(filter(fs_diffs, r2 >= 0), aes(x = r2)) +
  geom_histogram(bins = 20) +
  theme_bw() +
  facet_wrap(vars(s0, n0), scales = "free_y", ncol = 1)

ggplot(filter(fs_diffs, r2_log >= 0), aes(x = r2_log)) +
  geom_histogram(bins = 20) +
  theme_bw() +
  facet_wrap(vars(s0, n0), scales = "free_y", ncol = 1)

ggplot(fs_diffs, aes(x = cd)) +
  geom_histogram(bins = 20) +
  theme_bw() +
  facet_wrap(vars(s0, n0), scales = "free_y", ncol = 1)


ggplot(fs_diffs, aes(x = prop_off)) +
  geom_histogram(bins = 20) +
  theme_bw() +
  facet_wrap(vars(s0, n0), scales = "free_y", ncol = 1)
```

